import {z} from 'zod';
import {requireUser,requirePermission} from '@/lib/auth/guards';
import {sameOrigin} from '@/lib/security/origin';
import {rateLimit} from '@/lib/security/rate-limit';
import {checkDb,errorResponse,AppError} from '@/lib/errors';
import {inngest} from '@/inngest/client';
import {DOCUMENT_TYPES} from '@/lib/constants';
export const runtime='nodejs';
export async function POST(req:Request){try{const user=await requireUser();sameOrigin(req);if(Number(req.headers.get('content-length'))>21_000_000)throw new AppError('file_size','The file must be under 20 MB.');const f=await req.formData();const v=z.object({buildingId:z.uuid(),title:z.string().min(1).max(180),type:z.enum(DOCUMENT_TYPES),knowledgeBaseId:z.union([z.uuid(),z.literal('')]),effectiveDate:z.union([z.iso.date(),z.literal('')]),filingReference:z.string().max(100),consent:z.literal('on')}).parse(Object.fromEntries(f));await requirePermission(user,'vault.upload',v.buildingId);await rateLimit(v.buildingId,'upload');const file=f.get('file');if(!(file instanceof File)||file.size>20_971_520||file.size<1)throw new AppError('file_size','Choose a file under 20 MB.');const ext=file.name.split('.').pop()?.toLowerCase();const mime:Record<string,string>={pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',txt:'text/plain',md:'text/markdown'};if(!ext||!mime[ext])throw new AppError('file_type','Use a PDF, DOCX, TXT, or Markdown file.');const bytes=Buffer.from(await file.arrayBuffer());if(ext==='pdf'&&bytes.subarray(0,5).toString()!=='%PDF-')throw new AppError('file_type','The file does not appear to be a PDF.');if(ext==='docx'&&bytes.subarray(0,2).toString()!=='PK')throw new AppError('file_type','The file does not appear to be a DOCX.');const id=crypto.randomUUID();const path=v.buildingId+'/'+id+'/source.'+ext;
 const {error}=await user.client.from('documents').insert({id,building_id:v.buildingId,title:v.title,type:v.type,knowledge_base_id:v.knowledgeBaseId||null,effective_date:v.effectiveDate||null,lto_filing_ref:v.filingReference||null,storage_path:path,uploaded_by:user.id,byte_size:file.size});checkDb(error);const upload=await user.client.storage.from('vault').upload(path,bytes,{contentType:mime[ext],upsert:false});checkDb(upload.error);await inngest.send({name:'document/ingest',data:{documentId:id,buildingId:v.buildingId,actorId:user.id}});return Response.json({id},{status:201});}catch(e){return errorResponse(e);}}
