import {beforeAll,afterAll,describe,it,expect} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {vector} from '@electric-sql/pglite-pgvector';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';
import {readFile,readdir} from 'node:fs/promises';
import {createHmac} from 'node:crypto';
const db=new PGlite({extensions:{vector,pgcrypto,pg_trgm}});
const a='10000000-0000-4000-8000-000000000001',b='10000000-0000-4000-8000-000000000002',assistant='10000000-0000-4000-8000-000000000003',counsel='10000000-0000-4000-8000-000000000004';
let ba:string,bb:string,chat:string,notice:string;const sql=(s:string)=>db.exec(s);
const embedding=JSON.stringify([1,...Array(1023).fill(0)]);
async function identity(id:string){await sql("reset role; select set_config('request.jwt.claim.sub','"+id+"',false); set role authenticated;");}
async function admin(){await sql('reset role;');}
beforeAll(async()=>{
 await sql(`create role anon; create role authenticated; create role service_role bypassrls; create role supabase_auth_admin;
 create schema auth; create schema storage; create schema extensions;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth,storage,public to authenticated,anon,service_role,supabase_auth_admin;
 grant execute on function auth.uid() to authenticated,anon,service_role,supabase_auth_admin;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
 create function storage.foldername(name text) returns text[] language sql as $$ select string_to_array(name,'/') $$;
 grant select,insert on storage.objects to authenticated;`);
 for(const file of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await sql(await readFile('supabase/migrations/'+file,'utf8'));
 await sql(`insert into auth.users(id,email,email_confirmed_at) values ('${a}','alpha@example.test',now()),('${b}','beta@example.test',now()),('${assistant}','assistant@example.test',now()),('${counsel}','counsel@example.test',now());`);
 await identity(a);ba=String((await db.query<{id:string}>(`select public.bootstrap_workspace('Alpha','admin','Alpha building','Alice') id`)).rows[0].id);
 await identity(b);bb=String((await db.query<{id:string}>(`select public.bootstrap_workspace('Beta','single_building','Beta building','Bob') id`)).rows[0].id);
 await admin();await sql(`update public.profiles set account_type='multi_building' where id='${assistant}';insert into public.building_members(building_id,user_id,role) values('${ba}','${assistant}','portfolio_assistant');insert into public.building_members(building_id,user_id,role,expires_at) values('${ba}','${counsel}','external_counsel',now()-interval '1 day');`);
 await identity(a);chat=(await db.query<{id:string}>(`insert into public.chats(building_id,user_id) values('${ba}','${a}') returning id`)).rows[0].id;
 notice=(await db.query<{id:string}>(`insert into public.generated_documents(building_id,created_by,title,kind,body_md) values('${ba}','${a}','Draft','s135_notice','A sample draft for human review') returning id`)).rows[0].id;
 await admin();
 await sql(`insert into public.knowledge_bases(id,building_id,name) values('80000000-0000-4000-8000-000000000001','${bb}','Private KB');
 insert into public.documents(id,building_id,title,type,status,structure_confirmed,uploaded_by,effective_date) values('80000000-0000-4000-8000-000000000002','${bb}','Private garden rules','rules','ready',true,'${b}','2025-01-01');
 insert into public.document_chunks(document_id,building_id,chunk_index,content,embedding) values('80000000-0000-4000-8000-000000000002','${bb}',0,'The private garden closes at sunset.','${embedding}');
 insert into public.document_versions(document_id,building_id,content_hash) values('80000000-0000-4000-8000-000000000002','${bb}','test-hash');
 insert into public.agents(id,building_id,name,created_by) values('80000000-0000-4000-8000-000000000003','${bb}','Private agent','${b}');
 insert into public.agent_deployments(agent_id,building_id,version,config,deployed_by) values('80000000-0000-4000-8000-000000000003','${bb}',1,'{}','${b}');
 insert into public.bylaw_sets(id,building_id,title) values('80000000-0000-4000-8000-000000000004','${bb}','Private set');
 insert into public.bylaw_nodes(id,building_id,set_id,title,section_ref) values('80000000-0000-4000-8000-000000000005','${bb}','80000000-0000-4000-8000-000000000004','Private bylaw','1');
 insert into public.bylaw_versions(id,building_id,node_id,version,body,created_by) values('80000000-0000-4000-8000-000000000006','${bb}','80000000-0000-4000-8000-000000000005',1,'Private body','${b}');
 insert into public.bylaw_comments(building_id,version_id,user_id,body) values('${bb}','80000000-0000-4000-8000-000000000006','${b}','Private comment');
 insert into public.disputes(id,building_id,title,reference,opened_by) values('80000000-0000-4000-8000-000000000007','${bb}','Private dispute','TEST','${b}');
 insert into public.dispute_events(building_id,dispute_id,stage,occurred_at,summary,actor_id,idempotency_key) values('${bb}','80000000-0000-4000-8000-000000000007','reported',now(),'Private event','${b}',gen_random_uuid());
 insert into public.generated_documents(id,building_id,kind,title,body_md,created_by) values('80000000-0000-4000-8000-000000000008','${bb}','email','Private notice','Private body','${b}');
 insert into public.artifact_versions(building_id,artifact_id,body_md,edited_by) values('${bb}','80000000-0000-4000-8000-000000000008','Private version','${b}');
 insert into public.notifications(building_id,type,title,body) values('${bb}','test','Private update','Private notification');
 insert into public.invitations(building_id,email,role,invited_by,token_hash) values('${bb}','invite@example.test','council_member','${b}','test-token');`);
},60000);
afterAll(()=>db.close());
describe('Postgres scope and permissions',()=>{
 for(const table of ['knowledge_bases','documents','document_chunks','document_versions','agents','agent_deployments','bylaw_sets','bylaw_nodes','bylaw_versions','bylaw_comments','disputes','dispute_events','generated_documents','artifact_versions','notifications','invitations','audit_log'])it('hides known foreign UUID records in '+table,async()=>{await identity(a);expect((await db.query(`select id from public.${table} where building_id='${bb}'`)).rows).toHaveLength(0);});
 it('blocks explicit cross-building hybrid retrieval',async()=>{await identity(a);expect((await db.query(`select * from public.hybrid_search_building('${bb}','garden','${embedding}')`)).rows).toHaveLength(0);});
 it('returns the same passage to its authorized building member',async()=>{await identity(b);expect((await db.query(`select content from public.hybrid_search_building('${bb}','garden','${embedding}')`)).rows).toHaveLength(1);});
 it('filters out a document not yet effective on the conduct date',async()=>{await identity(b);expect((await db.query(`select content from public.hybrid_search_building('${bb}','garden','${embedding}',null,'2024-01-01')`)).rows).toHaveLength(0);});
 it('rejects denormalized chunk scope tampering at the foreign key',async()=>{await admin();await expect(sql(`insert into public.document_chunks(document_id,building_id,chunk_index,content,embedding) values('80000000-0000-4000-8000-000000000002','${ba}',1,'Forged scope','${embedding}')`)).rejects.toThrow();});
 it('enables RLS on every public table',async()=>{await admin();const r=await db.query(`select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and relkind='r' and not relrowsecurity`);expect(r.rows).toHaveLength(0);});
 it('hides a known building UUID from another tenant',async()=>{await identity(a);expect((await db.query(`select id from public.buildings where id='${bb}'`)).rows).toHaveLength(0);});
 it('isolates membership records',async()=>{await identity(a);expect((await db.query(`select id from public.building_members where building_id='${bb}'`)).rows).toHaveLength(0);});
 it('does not give owners access to another user’s conversations',async()=>{await identity(assistant);expect((await db.query(`select id from public.chats where id='${chat}'`)).rows).toHaveLength(0);});
 it('denies forged assistant turns through the Data API',async()=>{await identity(a);await expect(sql(`insert into public.messages(chat_id,role,parts) values('${chat}','assistant','[{"type":"text","text":"Fabricated prior answer"}]')`)).rejects.toThrow();});
 it('denies a forged verified-message signature',async()=>{await identity(a);await expect(sql(`select public.append_verified_message('${chat}',gen_random_uuid(),'[]','fake','wrong')`)).rejects.toThrow();});
 it('accepts a server-attested message with the caller’s scope',async()=>{await admin();const secret=(await db.query<{value:string}>("select value from private.runtime_secrets where name='server_signing'")).rows[0].value;const id='20000000-0000-4000-8000-000000000001';const parts='[{"type":"text","text":"Verified sample"}]';const signature=createHmac('sha256',secret).update(chat+':'+id+':'+parts).digest('hex');await identity(a);await db.query('select public.append_verified_message($1,$2,$3,$4,$5)',[chat,id,parts,'test',signature]);expect((await db.query(`select id from public.messages where chat_id='${chat}'`)).rows).toHaveLength(1);});
 it('denies cross-building chat creation',async()=>{await identity(a);await expect(sql(`insert into public.chats(building_id,user_id) values('${bb}','${a}')`)).rejects.toThrow();});
 it('prevents chat scope changes',async()=>{await identity(a);await expect(sql(`update public.chats set building_id='${bb}' where id='${chat}'`)).rejects.toThrow();});
 it('does not authorize expired counsel',async()=>{await identity(counsel);expect((await db.query(`select id from public.buildings where id='${ba}'`)).rows).toHaveLength(0);});
 it('blocks assistant approval and sending even when the UUID is known',async()=>{await identity(assistant);await expect(sql(`select public.transition_artifact('${notice}','approved')`)).rejects.toThrow();await expect(sql(`select public.transition_artifact('${notice}','sent',now())`)).rejects.toThrow();});
 it('blocks direct status and scope tampering',async()=>{await identity(a);await expect(sql(`update public.generated_documents set status='approved',approved_by='${a}',approved_at=now() where id='${notice}'`)).rejects.toThrow();await expect(sql(`update public.buildings set org_id=gen_random_uuid() where id='${ba}'`)).rejects.toThrow();});
 it('requires an independent approver for enforcement notices',async()=>{await identity(a);await sql(`select public.transition_artifact('${notice}','pending_review')`);await expect(sql(`select public.transition_artifact('${notice}','approved')`)).rejects.toThrow('self_approval_not_permitted');});
 it('does not permit editing or deleting the audit record',async()=>{await identity(a);await expect(sql('delete from public.audit_log')).rejects.toThrow();await expect(sql("update public.audit_log set action='forged'")).rejects.toThrow();});
 it('enforces a permanent single-building binding',async()=>{await admin();await expect(sql(`insert into public.building_members(building_id,user_id,role) values('${ba}','${b}','building_manager')`)).rejects.toThrow('single_building_bound');});
 it('uses caller security for both hybrid retrieval functions',async()=>{await admin();const r=await db.query<{prosecdef:boolean}>("select prosecdef from pg_proc where proname in ('hybrid_search_building','hybrid_search_legal')");expect(r.rows).toHaveLength(2);expect(r.rows.every(x=>!x.prosecdef)).toBe(true);});
 describe('invitations and existing members',()=>{
  const president='10000000-0000-4000-8000-000000000011',manager='10000000-0000-4000-8000-000000000012',newcomer='10000000-0000-4000-8000-000000000013';
  beforeAll(async()=>{await admin();await sql(`insert into auth.users(id,email,email_confirmed_at) values('${president}','president@example.test',now()),('${manager}','manager@example.test',now()),('${newcomer}','newcomer@example.test',now());
   update public.profiles set account_type='multi_building' where id='${manager}';
   insert into public.building_members(building_id,user_id,role) values('${ba}','${president}','council_president'),('${ba}','${manager}','portfolio_manager');`);});
  const roleOf=async(user:string)=>{await admin();return (await db.query<{role:string}>(`select role from public.building_members where building_id='${ba}' and user_id='${user}'`)).rows[0]?.role;};
  it('does not let a lower-ranked member invite an existing member',async()=>{await identity(president);await expect(sql(`select public.create_invitation('${ba}','manager@example.test','council_member','president-demote-hash',null)`)).rejects.toThrow('already_member');});
  it('does not change an existing member’s role when they accept an invitation',async()=>{await admin();await sql(`insert into public.invitations(building_id,email,role,invited_by,token_hash) values('${ba}','manager@example.test','council_member','${president}','stale-demote-hash')`);await identity(manager);await expect(sql(`select public.accept_invitation('stale-demote-hash')`)).rejects.toThrow('already_member');expect(await roleOf(manager)).toBe('portfolio_manager');});
  it('does not let a lower-ranked member revive a suspended higher-ranked membership',async()=>{const former='10000000-0000-4000-8000-000000000014';await admin();await sql(`insert into auth.users(id,email,email_confirmed_at) values('${former}','former@example.test',now());update public.profiles set account_type='multi_building' where id='${former}';insert into public.building_members(building_id,user_id,role,status) values('${ba}','${former}','portfolio_manager','suspended');`);await identity(president);await expect(sql(`select public.create_invitation('${ba}','former@example.test','council_member','revive-hash',null)`)).rejects.toThrow('forbidden');});
  it('still admits a new person through an invitation',async()=>{await identity(president);await sql(`select public.create_invitation('${ba}','newcomer@example.test','council_member','newcomer-hash',null)`);await identity(newcomer);await sql(`select public.accept_invitation('newcomer-hash')`);expect(await roleOf(newcomer)).toBe('council_member');});
 });
 describe('malware scan gate on stored files',()=>{
  const doc='80000000-0000-4000-8000-000000000021';let path:string;
  beforeAll(async()=>{path=`${ba}/${doc}/source.pdf`;await admin();await sql(`insert into public.documents(id,building_id,title,type,status,uploaded_by,storage_path) values('${doc}','${ba}','Unscanned upload','rules','scanning','${a}','${path}');insert into storage.objects(bucket_id,name) values('vault','${path}');`);});
  const visible=async()=>{await identity(a);return (await db.query(`select id from storage.objects where bucket_id='vault' and name='${path}'`)).rows.length;};
  it('does not serve a stored file before its malware scan clears',async()=>{expect(await visible()).toBe(0);});
  it('serves the stored file once the scan has cleared',async()=>{await admin();await sql(`update public.documents set scan_cleared_at=now() where id='${doc}'`);expect(await visible()).toBe(1);});
  it('does not let a member mark their own upload as scan-cleared',async()=>{await identity(a);await expect(sql(`insert into public.documents(building_id,title,uploaded_by,storage_path,scan_cleared_at) values('${ba}','Forged clearance','${a}','${ba}/forged/source.pdf',now())`)).rejects.toThrow();});
 });
 it('revokes access immediately without waiting for JWT refresh',async()=>{await admin();await sql(`update public.building_members set status='suspended' where user_id='${assistant}'`);await identity(assistant);expect((await db.query(`select id from public.buildings where id='${ba}'`)).rows).toHaveLength(0);});
});
