'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowRight} from 'lucide-react';
import {Brand,Button} from '@/components/ui';
import {authAction,onboardAction,acceptInviteAction} from '../actions';
import {DISCLAIMER} from '@/lib/constants';
export function AuthForm({mode,ready}:{mode:'login'|'signup'|'forgot'|'reset';ready:boolean}){const router=useRouter();const[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const title={login:'Welcome back.',signup:'Clarity starts here.',forgot:'Reset your password.',reset:'Choose a new password.'}[mode];return <div className="auth-screen"><aside className="auth-art"><Brand/><div className="auth-quote"><span className="eyebrow">THE KNOWLEDGE BEHIND YOUR BUILDING</span><h1>Your building.<br/>Your bylaws.<br/><em>A clearer answer.</em></h1><p>Bring your documents, decisions, and the evidence behind them together in one place.</p></div><span className="auth-footer">BUILT FOR BC STRATA · DESIGNED AROUND YOU</span></aside><main className="auth-main"><div className="auth-box"><div className="auth-mobile-brand"><Brand/></div><h2>{title}</h2><p>{mode==='signup'?'Create a secure workspace for your strata or portfolio.':mode==='login'?'Sign in to your BylawIQ workspace.':'We’ll help you securely regain access to your account.'}</p>
 {!ready&&<div className="inline-callout" style={{marginBottom:22}}>Your workspace services are being connected. You can <Link href="/preview/ask">explore the interface</Link> while setup is completed.</div>}
 <form className="form-stack auth-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const r=await authAction({mode,email:f.get('email'),password:mode==='forgot'?undefined:f.get('password'),consent:f.get('consent')==='on'});setBusy(false);if(!r.ok)setError(r.error||'Please try again.');else if(r.redirect)router.push(r.redirect);else setMessage(r.message||'Saved.');}}>
 <label>Email address<input type="email" name="email" required autoComplete="email" placeholder="you@company.com"/></label>{mode!=='forgot'&&<label>Password<input name="password" type="password" required minLength={12} autoComplete={mode==='login'?'current-password':'new-password'} placeholder={mode==='login'?'Enter your password':'At least 12 characters'}/></label>}
 {mode==='login'&&<Link style={{fontSize:11,alignSelf:'end'}} href="/forgot">Forgot password?</Link>}{mode==='signup'&&<><p className="form-note">Managing buildings separately? Plus-addressed emails such as manager+oakridge@company.com are supported.</p><label className="checkbox-label"><input name="consent" type="checkbox" required/><span>I acknowledge that BylawIQ provides legal information, requires human review, and processes the documents I am authorized to upload.</span></label></>}
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="success-note" role="status">{message}</p>}<Button type="submit" busy={busy} disabled={!ready}>{mode==='login'?'Sign in':mode==='signup'?'Create account':mode==='forgot'?'Send reset link':'Update password'}<ArrowRight size={16}/></Button></form>
 <p className="auth-switch">{mode==='login'?<>New to BylawIQ? <Link href="/signup">Create an account</Link></>:<>Already have an account? <Link href="/login">Sign in</Link></>}</p><p className="disclaimer">{DISCLAIMER}</p></div></main></div>;}
export function Onboarding(){const router=useRouter();const[type,setType]=useState('multi_building'),[busy,setBusy]=useState(false),[error,setError]=useState('');return <main className="onboarding"><Brand/><span className="eyebrow" style={{marginTop:45}}>LET’S MAKE THIS YOURS</span><h1>A workspace that fits your role.</h1><p className="form-note">Choose how you manage buildings. Access permissions are assigned separately, within each building.</p><div className="account-types">{[['admin','Organization admin','Manage your organization, buildings, and team.'],['multi_building','Portfolio manager','Work across the buildings assigned to you.'],['single_building','Building manager','A focused workspace permanently bound to one building.']].map(([value,title,desc])=><button key={value} className={'account-type '+(type===value?'selected':'')} onClick={()=>setType(value)}><strong>{title}</strong><small>{desc}</small></button>)}</div>
 <form className="form-stack card" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const r=await onboardAction({name:f.get('name'),organization:f.get('organization'),building:f.get('building'),accountType:type,consent:f.get('consent')==='on'});setBusy(false);if(r.ok)router.push('/b/'+r.buildingId+'/documents');else setError(r.error||'Please retry.');}}><div className="form-row"><label>Your name<input name="name" required minLength={2} autoComplete="name"/></label><label>Organization or strata name<input name="organization" required minLength={2}/></label></div><label>Your first building<input name="building" required minLength={2} placeholder="e.g. Oakridge Towers"/></label><label className="checkbox-label"><input type="checkbox" name="consent" required/><span>I am authorized to create this workspace and manage the building’s records.</span></label>{error&&<p role="alert" className="form-error">{error}</p>}<Button busy={busy}>Create workspace <ArrowRight size={16}/></Button></form><p className="disclaimer">{DISCLAIMER}</p></main>;}
export function InviteForm({token}:{token:string}){const router=useRouter();const[busy,setBusy]=useState(false),[error,setError]=useState('');return <main className="onboarding"><Brand/><h1>You’re invited.</h1><p>Sign in using the email address your invitation was sent to, then accept to join the building.</p><div className="action-line" style={{marginTop:25}}><Button busy={busy} onClick={async()=>{setBusy(true);const r=await acceptInviteAction(token);setBusy(false);if(r.ok)router.push('/b/'+r.buildingId+'/ask');else setError(r.error||'This invitation is unavailable.');}}>Accept invitation</Button><Link className="button button-secondary" href="/login">Sign in</Link></div>{error&&<p role="alert" className="form-error">{error}</p>}<p className="disclaimer">{DISCLAIMER}</p></main>;}
