'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {Building2,ChevronDown,PanelLeftClose,PanelLeftOpen,Plus,MessageSquare,BookOpen,Files,Mail,Bell,Settings,Users,Bot,Database,LayoutGrid,Search,LogOut,Scale,ShieldCheck,ArrowUpRight,Menu} from 'lucide-react';
import {Brand,Modal,Button,Badge} from './ui';
import type {Building,Profile} from '@/lib/schema';
import {signOutAction} from '@/features/auth/actions';
import {LinkedAccounts} from '@/features/members/linked-accounts';
const navigation=[['ask','Ask BylawIQ',MessageSquare],['bylaws','Bylaws',BookOpen],['documents','Documents',Files],['notices','Notices',Mail],['disputes','Disputes',Scale],['updates','Updates',Bell],['agents','AI agents',Bot],['knowledge','Knowledge bases',Database],['members','Team members',Users],['settings','Settings',Settings]] as const;
// Phone-width bottom bar (below 900px). Everything else stays in the slide-out menu behind "More".
const tabs=[['ask','Ask',MessageSquare],['bylaws','Bylaws',BookOpen],['documents','Documents',Files],['updates','Updates',Bell]] as const;
export function Shell({profile,buildings,activeId,children,preview=false,unreadUpdates=0}:{profile:Profile;buildings:Building[];activeId?:string;children:React.ReactNode;preview?:boolean;unreadUpdates?:number}){
 const pathname=usePathname(),router=useRouter();const[mobile,setMobile]=useState(false),[switcher,setSwitcher]=useState(false),[search,setSearch]=useState('');
 const active=buildings.find(b=>b.id===activeId)||buildings[0];const root=preview?'/preview':active?'/b/'+active.id:'/workspace';const href=(section:string)=>root+'/'+section;
 useEffect(()=>{function key(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();router.push(href('ask'));}if((e.metaKey||e.ctrlKey)&&e.key==='b'&&profile.account_type!=='single_building'){e.preventDefault();setSwitcher(true);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a>{mobile&&<button className="mobile-overlay" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <aside className={'sidebar '+(mobile?'sidebar-open':'')}><Link href={preview?'/preview':profile.account_type==='single_building'?href('ask'):'/workspace'} className="logo-link"><Brand/></Link>
 <button className="workspace-picker" onClick={()=>profile.account_type!=='single_building'&&setSwitcher(true)} aria-label="Select building" disabled={profile.account_type==='single_building'}><span className="building-avatar"><Building2 size={21}/></span><span><strong>{active?.name||'Your workspace'}</strong><small>{profile.account_type==='single_building'?'Building workspace':'Management workspace'}</small></span>{profile.account_type!=='single_building'&&<ChevronDown size={15}/>}</button>
 <Link onClick={()=>setMobile(false)} className="new-chat" href={href('ask')}><Plus size={17}/>New conversation<span>⌘ K</span></Link>
 <nav aria-label="Main navigation">{profile.account_type!=='single_building'&&<Link onClick={()=>setMobile(false)} className={pathname==='/workspace'?'nav-item active':'nav-item'} href={preview?'/preview/portfolio':'/workspace'}><LayoutGrid size={18}/>Overview</Link>}{navigation.map(([slug,label,Icon],i)=><div key={slug}>{(i===6||i===8)&&<div className="nav-label">{i===6?'INTELLIGENCE':'WORKSPACE'}</div>}<Link onClick={()=>setMobile(false)} className={'nav-item '+(pathname.includes('/'+slug)?'active':'')} href={href(slug)}><Icon size={18}/>{label}{slug==='ask'&&<span className="ai-tag">AI</span>}</Link></div>)}</nav>
 <div className="sidebar-bottom"><div className="privacy-mini"><ShieldCheck size={17}/><span>Private to your building</span></div><button className="user-menu" onClick={()=>router.push(href('settings'))}><span className="avatar">{(profile.display_name||'You').split(' ').map(w=>w[0]).slice(0,2).join('')}</span><span><strong>{profile.display_name||'Your account'}</strong><small>{profile.account_type==='admin'?'Organization admin':profile.account_type==='multi_building'?'Portfolio manager':'Building member'}</small></span><Settings size={15}/></button></div></aside>
 <div className="main-column"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(!mobile)}>{mobile?<PanelLeftClose size={20}/>:<PanelLeftOpen size={20}/>}</button><span className="breadcrumb">Workspace <span>/</span> <strong>{active?.name||'Overview'}</strong></span></div><div className="topbar-right"><LinkedAccounts preview={preview}/>{preview&&<Badge tone="warning">Sample workspace</Badge>}<button className="search-shortcut" onClick={()=>router.push(href('ask'))}><Search size={16}/><span>Ask a question</span><kbd>⌘ K</kbd></button><Link className="icon-button" aria-label="Updates" href={href('updates')}><Bell size={18}/></Link><span className="avatar avatar-small">{profile.display_name[0]||'B'}</span></div></header>
 {preview&&<div className="preview-banner">Fictional sample data · Explore the interface. <Link href="/signup">Create your workspace <ArrowUpRight size={13}/></Link></div>}
 <main id="main" className="workspace-main">{children}</main></div>
 <nav className="tab-bar" aria-label="Sections">{tabs.map(([slug,label,Icon])=>{const current=pathname.includes('/'+slug)||(slug==='ask'&&(pathname.includes('/chat/')||pathname.endsWith('/conversation')));return <Link key={slug} href={href(slug)} onClick={()=>setMobile(false)} className={'tab'+(current?' tab-active':'')} aria-current={current?'page':undefined}><span className="tab-icon"><Icon size={21} strokeWidth={current?2:1.6}/>{slug==='updates'&&unreadUpdates>0&&<span className="tab-badge" aria-hidden="true">{unreadUpdates>99?'99+':unreadUpdates}</span>}</span><span className="tab-label">{label}{slug==='updates'&&unreadUpdates>0&&<span className="sr-only">, {unreadUpdates} new</span>}</span></Link>;})}
 <button type="button" className={'tab'+(mobile?' tab-active':'')} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><span className="tab-icon"><Menu size={21} strokeWidth={1.6}/></span><span className="tab-label">More</span></button></nav>
 <Modal open={switcher} onOpenChange={setSwitcher} title="Choose a building" description="Each building opens its own workspace and conversation history."><div className="search-field"><Search size={18}/><input aria-label="Search buildings" placeholder="Search your buildings…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="building-options">{buildings.filter(b=>b.name.toLowerCase().includes(search.toLowerCase())).map(b=><button key={b.id} onClick={()=>{setSwitcher(false);router.push(preview?'/preview/ask':'/b/'+b.id+'/ask');}}><Building2/><span><strong>{b.name}</strong><small>{b.strata_plan_no||'Strata plan not set'} · {b.unit_count||'—'} units</small></span>{b.id===active?.id&&<Badge tone="blue">Current</Badge>}</button>)}</div>{!preview&&<Button variant="ghost" onClick={async()=>{await signOutAction();router.push('/login');}}><LogOut size={16}/>Sign out</Button>}</Modal>
 </div>;
}
