'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {Building2,ChevronDown,PanelLeftClose,PanelLeftOpen,Plus,MessageSquare,BookOpen,Files,Mail,Bell,Settings,Users,Bot,Database,LayoutGrid,Search,LogOut,Scale,ShieldCheck,Menu} from 'lucide-react';
import {Brand,Modal,Button,Badge} from './ui';
import type {Building,Profile} from '@/lib/schema';
import {useBackend} from './backend';
import {LinkedAccounts} from '@/features/members/linked-accounts';
// Each item names the permission it needs (spec §3.5); items the user lacks are hidden. The group heads the first visible item of a group.
const navigation=[['ask','Ask BylawIQ',MessageSquare,'chat.use',''],['bylaws','Bylaws',BookOpen,'building.read',''],['documents','Documents',Files,'vault.read',''],['notices','Notices',Mail,'chat.use',''],['disputes','Disputes',Scale,'dispute.read',''],['updates','Updates',Bell,'building.read',''],['agents','AI agents',Bot,'agent.manage','INTELLIGENCE'],['knowledge','Knowledge bases',Database,'agent.manage','INTELLIGENCE'],['members','Team members',Users,'member.read','WORKSPACE'],['settings','Settings',Settings,'building.read','WORKSPACE']] as const;
// Phone-width bottom bar (below 900px). Everything else stays in the slide-out menu behind "More".
const tabs=[['ask','Ask',MessageSquare,'chat.use'],['bylaws','Bylaws',BookOpen,'building.read'],['documents','Documents',Files,'vault.read'],['updates','Updates',Bell,'building.read']] as const;
export function Shell({profile,buildings,activeId,children,permissions=[],unreadUpdates=0}:{profile:Profile;buildings:Building[];activeId?:string;children:React.ReactNode;permissions?:string[];unreadUpdates?:number}){
 const pathname=usePathname(),router=useRouter(),{base,signOut}=useBackend();const can=(p:string)=>permissions.includes(p);const items=navigation.filter(n=>can(n[3])),bar=tabs.filter(t=>can(t[3]));const[mobile,setMobile]=useState(false),[switcher,setSwitcher]=useState(false),[search,setSearch]=useState('');
 const active=buildings.find(b=>b.id===activeId)||buildings[0];const root=base+(active?'/b/'+active.id:'/workspace');const href=(section:string)=>root+'/'+section;
 useEffect(()=>{function key(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'&&can('chat.use')){e.preventDefault();router.push(href('ask'));}if((e.metaKey||e.ctrlKey)&&e.key==='b'&&profile.account_type!=='single_building'){e.preventDefault();setSwitcher(true);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a>{mobile&&<button className="mobile-overlay" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <aside className={'sidebar '+(mobile?'sidebar-open':'')}><Link href={profile.account_type==='single_building'?href('ask'):base+'/workspace'} className="logo-link"><Brand/></Link>
 <button className="workspace-picker" onClick={()=>profile.account_type!=='single_building'&&setSwitcher(true)} aria-label="Select building" disabled={profile.account_type==='single_building'}><span className="building-avatar"><Building2 size={21}/></span><span><strong>{active?.name||'Your workspace'}</strong><small>{profile.account_type==='single_building'?'Building workspace':'Management workspace'}</small></span>{profile.account_type!=='single_building'&&<ChevronDown size={15}/>}</button>
 {can('chat.use')&&<Link onClick={()=>setMobile(false)} className="new-chat" href={href('ask')}><Plus size={17}/>New conversation<span>⌘ K</span></Link>}
 <nav aria-label="Main navigation">{profile.account_type!=='single_building'&&<Link onClick={()=>setMobile(false)} className={pathname===base+'/workspace'?'nav-item active':'nav-item'} href={base+'/workspace'}><LayoutGrid size={18}/>Overview</Link>}{items.map(([slug,label,Icon,,group],i)=><div key={slug}>{group&&group!==items[i-1]?.[4]&&<div className="nav-label">{group}</div>}<Link onClick={()=>setMobile(false)} className={'nav-item'+(pathname.includes('/'+slug)?' active':'')+(bar.some(([tab])=>tab===slug)?' in-tab-bar':'')} href={href(slug)}><Icon size={18}/>{label}{slug==='ask'&&<span className="ai-tag">AI</span>}</Link></div>)}</nav>
 <div className="sidebar-bottom"><div className="privacy-mini"><ShieldCheck size={17}/><span>Private to your building</span></div><button className="user-menu" disabled={!can('building.read')} onClick={()=>router.push(href('settings'))}><span className="avatar">{(profile.display_name||'You').split(' ').map(w=>w[0]).slice(0,2).join('')}</span><span><strong>{profile.display_name||'Your account'}</strong><small>{profile.account_type==='admin'?'Organization admin':profile.account_type==='multi_building'?'Portfolio manager':'Building member'}</small></span><Settings size={15}/></button></div></aside>
 <div className="main-column"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(!mobile)}>{mobile?<PanelLeftClose size={20}/>:<PanelLeftOpen size={20}/>}</button><span className="breadcrumb"><span className="breadcrumb-root">Workspace</span><span className="breadcrumb-sep" aria-hidden="true">/</span><strong>{active?.name||'Overview'}</strong></span></div><div className="topbar-right"><LinkedAccounts/>{can('chat.use')&&<button className="search-shortcut" onClick={()=>router.push(href('ask'))}><Search size={16}/><span>Ask a question</span><kbd>⌘ K</kbd></button>}{can('building.read')&&<Link className="icon-button topbar-updates" aria-label="Updates" href={href('updates')}><Bell size={18}/></Link>}<span className="avatar avatar-small">{profile.display_name[0]||'B'}</span></div></header>
 <main id="main" className="workspace-main">{children}</main></div>
 <nav className="tab-bar" aria-label="Sections">{bar.map(([slug,label,Icon])=>{const current=pathname.includes('/'+slug)||(slug==='ask'&&(pathname.includes('/chat/')||pathname.endsWith('/conversation')));return <Link key={slug} href={href(slug)} onClick={()=>setMobile(false)} className={'tab'+(current?' tab-active':'')} aria-current={current?'page':undefined}><span className="tab-icon"><Icon size={21} strokeWidth={current?2:1.6}/>{slug==='updates'&&unreadUpdates>0&&<span className="tab-badge" aria-hidden="true">{unreadUpdates>99?'99+':unreadUpdates}</span>}</span><span className="tab-label">{label}{slug==='updates'&&unreadUpdates>0&&<span className="sr-only">, {unreadUpdates} new</span>}</span></Link>;})}
 <button type="button" className={'tab'+(mobile?' tab-active':'')} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><span className="tab-icon"><Menu size={21} strokeWidth={1.6}/></span><span className="tab-label">More</span></button></nav>
 <Modal open={switcher} onOpenChange={setSwitcher} title="Choose a building" description="Each building opens its own workspace and conversation history."><div className="search-field"><Search size={18}/><input aria-label="Search buildings" placeholder="Search your buildings…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="building-options">{buildings.filter(b=>b.name.toLowerCase().includes(search.toLowerCase())).map(b=><button key={b.id} onClick={()=>{setSwitcher(false);router.push(base+'/b/'+b.id+'/ask');}}><Building2/><span><strong>{b.name}</strong><small>{b.strata_plan_no||'Strata plan not set'} · {b.unit_count||'—'} units</small></span>{b.id===active?.id&&<Badge tone="blue">Current</Badge>}</button>)}</div><Button variant="ghost" onClick={async()=>{await signOut();router.push(base||'/login');}}><LogOut size={16}/>Sign out</Button></Modal>
 </div>;
}
