import type {Building,Profile,Row} from '@/lib/schema';
import type {BylawMessage} from '@/lib/chat-types';
export const demoBuilding:Building={id:'10000000-0000-4000-8000-000000000001',org_id:'20000000-0000-4000-8000-000000000001',name:'Oakridge Towers',strata_plan_no:'SAMPLE · EPS 4482',address:'Vancouver, British Columbia',unit_count:148,municipality:'Vancouver',corpus_version:1,jurisdiction_chain:[]};
export const demoProfile:Profile={id:'30000000-0000-4000-8000-000000000001',display_name:'Alex Morgan',account_type:'multi_building',bound_building_id:null};
export const demoBuildings=[demoBuilding,{...demoBuilding,id:'10000000-0000-4000-8000-000000000002',name:'Cedar Court',unit_count:64,strata_plan_no:'SAMPLE · LMS 2910'},{...demoBuilding,id:'10000000-0000-4000-8000-000000000003',name:'Harbour House',unit_count:92,strata_plan_no:'SAMPLE · EPS 1027'}];
const id=(n:number)=>'40000000-0000-4000-8000-'+String(n).padStart(12,'0');const row=(n:number,title:string,extra:Record<string,unknown>={}):Row=>({id:id(n),building_id:demoBuilding.id,title,created_at:'2026-09-12T09:30:00Z',...extra});
export const demoData:Record<string,Row[]>={
 documents:[row(1,'Registered bylaws · Consolidated 2025',{type:'bylaws',status:'ready',byte_size:248320,effective_date:'2025-03-12',parsed_sections:[{heading:'Visitor parking',content:'Sample only: visitor spaces are reserved for guests.'},{heading:'Pets & animals',content:'Sample only: review pet and accommodation provisions together.'},{heading:'Quiet hours',content:'Sample only: quiet hours run from 10 pm until 7 am.'}]}),row(2,'Council meeting minutes · September',{type:'council_minutes',status:'ready',byte_size:152000}),row(3,'Building rules · Common areas',{type:'rules',status:'ready',byte_size:98000}),row(4,'Insurance summary · 2026–2027',{type:'insurance',status:'review',byte_size:182000}),row(5,'Strata plan · Original filing',{type:'strata_plan',status:'ready',byte_size:732000}),row(6,'AGM minutes · March 2026',{type:'agm_minutes',status:'ready',byte_size:233000})],
 chats:[row(11,'Can residents use visitor parking?',{scope:'building',archived:false}),row(12,'What do our pet bylaws say?',{scope:'building',archived:false}),row(13,'Summarize our last council meeting',{scope:'building',archived:false})],
 knowledge:[row(21,'',{name:'Building bylaws & rules',description:'Registered bylaws, amendments, and the rules that apply to shared spaces.'}),row(22,'',{name:'Council records',description:'Meeting minutes, resolutions, and your building’s decision history.'}),row(23,'',{name:'Building reference',description:'Plans, reports, insurance, and other supporting information.'})],
 agents:[row(31,'',{name:'Bylaw intelligence',description:'Find clear answers in your current registered bylaws and supporting sources.',instructions:'Help council members understand the building’s provisions.',status:'deployed',knowledge_base_id:id(21),include_legal:true,top_k:8}),row(32,'',{name:'Council assistant',description:'Turn meeting records into concise summaries and evidence-backed action lists.',status:'deployed',knowledge_base_id:id(22),include_legal:true,top_k:8}),row(33,'',{name:'Visitor parking guide',description:'Bring visitor parking rules, registration details, and signage requirements together.',status:'draft',knowledge_base_id:id(21),include_legal:true,top_k:6})],
 bylaws:[row(41,'Quiet hours & nuisance',{section_ref:'3.1'}),row(42,'Pets & animals',{section_ref:'3.2'}),row(43,'Visitor parking',{section_ref:'4.1'}),row(44,'Electric vehicle charging',{section_ref:'4.3'})],
 versions:[row(51,'',{node_id:id(41),version:1,status:'in_force',body:'FICTIONAL SAMPLE\nResidents and visitors must observe quiet hours between 10:00 pm and 7:00 am.',effective_date:'2025-03-12',rationale:'Sample current version'}),row(52,'',{node_id:id(42),version:1,status:'in_force',body:'FICTIONAL SAMPLE\nReview the complete pet and accommodation provisions before making a decision.',effective_date:'2025-03-12'}),row(53,'',{node_id:id(43),version:1,status:'in_force',body:'FICTIONAL SAMPLE\nVisitor parking spaces are reserved for guests of the building.',effective_date:'2025-03-12'}),row(54,'',{node_id:id(44),version:1,status:'draft',body:'FICTIONAL SAMPLE\nDraft a process for reviewing requests for electric vehicle charging.'})],
 notices:[row(61,'Visitor parking · Draft response',{kind:'email',body_md:'FICTIONAL SAMPLE\n\nThank you for your parking enquiry. Please review the complete visitor parking provisions and contact the manager with the relevant circumstances.',status:'draft',created_by:demoProfile.id}),row(62,'September council report',{kind:'council_report',body_md:'FICTIONAL SAMPLE\n\nFor council review: confirm the current document set and review the proposed EV charging amendment.',status:'pending_review',created_by:demoProfile.id})],
 disputes:[row(71,'Visitor parking enquiry · Unit 304',{reference:'SAMPLE-001',category:'parking',subject_unit:'304',stage:'investigating'}),row(72,'Noise enquiry · Common area',{reference:'SAMPLE-002',category:'noise',stage:'reported'})],
 events:[row(73,'',{dispute_id:id(71),stage:'reported',summary:'Fictional sample: parking enquiry received for manager review.',occurred_at:'2026-09-11T10:00:00Z',logged_at:'2026-09-11T11:00:00Z'})],
 updates:[row(81,'Review your new document structure',{type:'document_review',body:'Your insurance summary is ready for a human check before it becomes searchable.',severity:'info',state:'new'}),row(82,'EV charging amendment is still a draft',{type:'draft_review',body:'Arrange a legal review and verify the supporting records before proposing the amendment.',severity:'warning',state:'new'})],
 members:[row(91,'Alex Morgan',{user_id:demoProfile.id,role:'portfolio_manager',status:'active'}),row(92,'Jordan Lee',{user_id:'30000000-0000-4000-8000-000000000002',role:'portfolio_assistant',status:'active'}),row(93,'Sam Chen',{user_id:'30000000-0000-4000-8000-000000000003',role:'council_president',status:'active'}),row(94,'Taylor Park',{user_id:'30000000-0000-4000-8000-000000000004',role:'council_member',status:'active'})],
 audit:[row(95,'',{action:'documents.insert',occurred_at:'2026-09-12T09:30:00Z',actor_id:demoProfile.id})],
 organizations:[{id:demoBuilding.org_id,name:'Northline Strata Management',letterhead:'Northline Strata Management',signature_block:'The management team'}],invitations:[],
};
export const demoPermissions=['building.read','building.create','building.update','vault.read','vault.upload','vault.delete','chat.use','chat.use_portfolio','bylaw.edit','bylaw.adopt','document.draft','document.approve','document.send','dispute.read','dispute.create','dispute.update','member.read','member.invite','member.update_role','audit.read','agent.manage','agent.deploy'];
export const demoConversation:BylawMessage[]=[{id:id(101),role:'user',parts:[{type:'text',text:'Can residents use visitor parking?'}]},{id:id(102),role:'assistant',parts:[{type:'data-answer',id:'grounded-answer',data:{answer:{answer:[{text:'In this fictional example, visitor parking spaces are reserved for guests of the building.',evidence:[{source:1,quote:'Visitor parking spaces are reserved for guests of the building.'}]}],basis:[{text:'The sample provision describes who the spaces are reserved for.',evidence:[{source:1,quote:'Visitor parking spaces are reserved for guests of the building.'}]}],nextSteps:[{text:'Review the full parking section before responding to the resident.',evidence:[{source:1,quote:'Review the full parking section before responding to the resident.'}]}],limitations:'Illustrative only. No real building documents or live legal sources were searched.'},sources:[{id:1,chunkId:id(103),kind:'building',title:'Fictional registered bylaws · Visitor parking',content:'Visitor parking spaces are reserved for guests of the building. Review the full parking section before responding to the resident.',sectionRef:'4.1',effectiveDate:'2025-03-12',buildingId:demoBuilding.id,page:7,citation:null}]}}]}];
