// Topic tags for imported BC legislation, keyed by section number as published.
// tools/import-bclaws.ts applies these on every run, so change topics here, not in the items.
// Tag only where the section is plainly about the topic; most sections have no tag, and they
// are still found by section number and full text. Every id must exist in taxonomy/topics.json,
// and every section number must exist in the import (the importer checks both).

type TopicMap = Record<string, string[]>;

const range = (from: number, to: number, topics: string[]): TopicMap =>
  Object.fromEntries(Array.from({ length: to - from + 1 }, (_, i) => [String(from + i), topics]));

/** Strata Property Act, SBC 1998, c 43 (sections of the Act, not the Schedule). */
export const SPA_TOPICS: TopicMap = {
  '3': ['repair-maintenance', 'common-property-use'],
  '4': ['council-governance'],
  ...range(25, 34, ['council-governance']),
  '34.1': ['hearings', 'council-governance'],
  '35': ['privacy-records'],
  '36': ['privacy-records'],
  '37': ['privacy-records'],
  '38': ['council-governance'],
  '39': ['council-governance'],
  ...range(40, 58, ['general-meetings-voting']),
  '59': ['privacy-records'],
  '66': ['common-property-use'],
  '70': ['alterations-renovations'],
  '71': ['common-property-use', 'alterations-renovations'],
  '72': ['repair-maintenance'],
  '73': ['limited-common-property'],
  '74': ['limited-common-property'],
  '75': ['limited-common-property'],
  '76': ['common-property-use'],
  '77': ['common-property-use', 'repair-maintenance'],
  '80': ['common-property-use'],
  '90.1': ['ev-charging', 'alterations-renovations', 'common-property-use'],
  '90.2': ['ev-charging', 'alterations-renovations', 'common-property-use'],
  '90.3': ['ev-charging', 'alterations-renovations', 'common-property-use'],
  '92': ['contingency-reserve-fund'],
  '93': ['contingency-reserve-fund'],
  '94': ['depreciation-report'],
  '94.1': ['electrical-planning-reports', 'ev-charging'],
  '95': ['contingency-reserve-fund'],
  '96': ['contingency-reserve-fund', 'depreciation-report'],
  '99': ['strata-fees-arrears'],
  '100': ['strata-fees-arrears'],
  '101': ['strata-fees-arrears', 'contingency-reserve-fund'],
  '106': ['strata-fees-arrears'],
  '107': ['strata-fees-arrears'],
  '108': ['special-levies'],
  '109': ['special-levies'],
  '110': ['common-property-use'],
  ...range(112, 118, ['strata-fees-arrears']),
  '121': ['human-rights-accommodation'],
  '123': ['pets'],
  '123.1': ['human-rights-accommodation'],
  '123.2': ['human-rights-accommodation'],
  '126': ['bylaw-amendment-filing'],
  '127': ['bylaw-amendment-filing'],
  '128': ['bylaw-amendment-filing'],
  '129': ['bylaw-enforcement-s135'],
  '130': ['fines', 'bylaw-enforcement-s135'],
  '131': ['fines', 'rentals'],
  '132': ['fines'],
  '133': ['bylaw-enforcement-s135'],
  '134': ['bylaw-enforcement-s135', 'common-property-use'],
  '135': ['bylaw-enforcement-s135', 'fines', 'hearings'],
  '136': ['bylaw-enforcement-s135', 'council-governance'],
  '137': ['bylaw-enforcement-s135', 'rentals'],
  '138': ['bylaw-enforcement-s135', 'rentals'],
  '141': ['rentals'],
  '146': ['rentals'],
  '147': ['rentals'],
  '148': ['rentals'],
  ...range(149, 162, ['insurance-deductibles']),
  '189.1': ['crt-process'],
  '189.4': ['crt-process'],
  '256': ['strata-fees-arrears'],
  '257': ['limited-common-property'],
  '258': ['parking', 'limited-common-property'],
};

/** Schedule of Standard Bylaws, keyed by standard bylaw section number. */
export const STANDARD_BYLAW_TOPICS: TopicMap = {
  '1': ['strata-fees-arrears'],
  '2': ['repair-maintenance'],
  '3': ['nuisance', 'noise', 'pets', 'common-property-use'],
  '5': ['alterations-renovations'],
  '6': ['alterations-renovations', 'common-property-use'],
  '7': ['repair-maintenance', 'hoarding-safety'],
  '8': ['repair-maintenance', 'limited-common-property'],
  ...range(9, 14, ['council-governance']),
  ...range(16, 22, ['council-governance']),
  '23': ['fines'],
  '24': ['fines'],
  ...range(25, 28, ['general-meetings-voting']),
};

/** Strata Property Regulation, BC Reg 43/2000. */
export const SPR_TOPICS: TopicMap = {
  '3.01': ['contingency-reserve-fund'],
  '3.4': ['contingency-reserve-fund'],
  '4.01': ['hearings'],
  '4.1': ['privacy-records'],
  '4.2': ['privacy-records'],
  '4.3': ['privacy-records'],
  '4.4': ['privacy-records'],
  '5.3': ['ev-charging', 'alterations-renovations', 'common-property-use'],
  '5.4': ['ev-charging', 'electrical-planning-reports'],
  '5.5': ['ev-charging'],
  '5.6': ['ev-charging', 'alterations-renovations'],
  '5.7': ['electrical-planning-reports'],
  '5.8': ['electrical-planning-reports'],
  '5.9': ['electrical-planning-reports'],
  '5.10': ['electrical-planning-reports'],
  '5.11': ['electrical-planning-reports', 'ev-charging'],
  '5.12': ['electrical-planning-reports'],
  '5.101': ['ev-charging', 'parking', 'common-property-use'],
  '6.1': ['contingency-reserve-fund'],
  '6.2': ['depreciation-report'],
  '6.21': ['depreciation-report'],
  '6.22': ['depreciation-report'],
  '6.23': ['depreciation-report', 'contingency-reserve-fund'],
  '6.3': ['contingency-reserve-fund'],
  '6.4': ['strata-fees-arrears', 'special-levies'],
  '6.5': ['strata-fees-arrears', 'special-levies'],
  '6.8': ['strata-fees-arrears', 'special-levies'],
  '6.9': ['common-property-use'],
  '6.10': ['strata-fees-arrears'],
  '6.11': ['contingency-reserve-fund', 'special-levies'],
  '7.01': ['human-rights-accommodation'],
  '7.1': ['fines', 'short-term-rentals'],
  '7.2': ['bylaw-enforcement-s135', 'hearings'],
  '9.1': ['insurance-deductibles'],
  '9.2': ['insurance-deductibles'],
  '9.3': ['insurance-deductibles'],
  '17.7': ['common-property-use'],
  '17.8': ['strata-fees-arrears'],
  '17.9': ['strata-fees-arrears'],
  '17.12': ['pets'],
  '17.19': ['parking'],
  '17.23': ['general-meetings-voting'],
};

/**
 * Strata Property Regulation, Schedule of Forms, keyed by the form letter as published.
 * Tagged only where the form is plainly about the topic. Forms with no tag are still found by
 * their letter, their name and their full text.
 */
export const FORM_TOPICS: TopicMap = {
  'A': ['general-meetings-voting'],
  'B': ['privacy-records', 'strata-fees-arrears', 'insurance-deductibles', 'depreciation-report', 'electrical-planning-reports'],
  'E': ['privacy-records'],
  'F': ['strata-fees-arrears'],
  'G': ['strata-fees-arrears'],
  'H': ['strata-fees-arrears'],
  'I': ['bylaw-amendment-filing'],
  'K': ['rentals', 'bylaw-enforcement-s135'],
  'L': ['crt-process'],
  'M': ['crt-process'],
  'N': ['crt-process'],
  'Y': ['bylaw-amendment-filing'],
};
