'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Button,Modal} from '@/components/ui';
import {mutateAction} from '../actions';
import type {Row} from '@/lib/schema';
export type Field={name:string;label:string;type?:'text'|'textarea'|'number'|'date'|'datetime-local'|'email'|'checkbox'|'select';options?:{value:string;label:string}[];required?:boolean;hint?:string;value?:string|number|boolean;min?:number;max?:number};
export function ResourceForm({open,onClose,title,description,buildingId,operation,id,fields,extra={},preview=false,onSaved}:{open:boolean;onClose:()=>void;title:string;description?:string;buildingId:string;operation:string;id?:string;fields:Field[];extra?:Record<string,unknown>;preview?:boolean;onSaved?:(r:{id?:string;url?:string})=>void}){const router=useRouter();const[busy,setBusy]=useState(false),[error,setError]=useState(''),[link,setLink]=useState('');return <Modal open={open} onOpenChange={v=>!v&&onClose()} title={title} description={description}><form onSubmit={async e=>{e.preventDefault();setError('');if(preview){setError('This is a sample workspace. Create your account to save real records.');return;}const data=new FormData(e.currentTarget);const values:Record<string,unknown>={...extra};for(const f of fields){const v=data.get(f.name);values[f.name]=f.type==='checkbox'?v==='on':f.type==='number'?(v===''?null:Number(v)):f.type==='datetime-local'?(v?new Date(String(v)).toISOString():null):f.type==='date'?(v||null):v;}setBusy(true);const r=await mutateAction({buildingId,operation,id,values});setBusy(false);if(!r.ok){setError(r.error);return;}onSaved?.(r);router.refresh();if(r.url)setLink(r.url);else onClose();}}><div className="form-stack">{fields.map(f=>f.type==='checkbox'?<label className="checkbox-label" key={f.name}><input name={f.name} type="checkbox" defaultChecked={Boolean(f.value)} required={f.required}/><span>{f.label}</span></label>:<label key={f.name}>{f.label}{f.type==='textarea'?<textarea name={f.name} defaultValue={String(f.value||'')} required={f.required} rows={5}/>:f.type==='select'?<select name={f.name} defaultValue={String(f.value??'')} required={f.required}>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input name={f.name} type={f.type||'text'} defaultValue={typeof f.value==='boolean'?'':f.value} required={f.required} min={f.min} max={f.max}/>} {f.hint&&<span className="form-note">{f.hint}</span>}</label>)}</div>{error&&<p className="form-error" role="alert" style={{marginTop:16}}>{error}</p>}{link&&<div className="link-output"><p>Invitation created. Share this private link with the intended recipient:</p><a href={link}>{link}</a><Button variant="secondary" size="small" type="button" onClick={()=>navigator.clipboard.writeText(link)}>Copy invitation link</Button></div>}<div className="form-footer"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" busy={busy}>{operation==='member.invite'?'Create invitation':'Save changes'}</Button></div></form></Modal>;}
export const str=(row:Row,key:string,fallback='')=>typeof row[key]==='string'?row[key] as string:typeof row[key]==='number'?String(row[key]):fallback;
